[package]
name = "aoc_2021"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arraymap = "0.1.1"
petgraph = "0.6.0"

[profile.release]
debug = true